name = "bind_RBM"
uuid = "b654bff8-ca72-46a9-9ffa-e55dbf73f8c2"
version = "0.1.0"
authors = ["JacopoBoccato <jacopo.boccato@gmail.com>"]

[deps]
AdvRBMs = "5c8d321f-d88f-4112-b4bc-67901fc2de0a"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"
SequenceLogos = "7a3f67ce-6eeb-4904-9da4-2cbd106a5944"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
AdvRBMs = "2.1.0"
CairoMakie = "0.15.8"
Clustering = "0.15.8"
DataFrames = "1.8.1"
Dates = "1.11.0"
DelimitedFiles = "1.9.1"
Distances = "0.10.12"
Flux = "0.16.8"
IJulia = "1.34.0"
JLD2 = "0.6.3"
LIBSVM = "0.8.1"
LinearAlgebra = "1.12.0"
MLJ = "0.22.0"
MLJLinearModels = "0.10.1"
Makie = "0.24.8"
Measures = "0.3.3"
MultivariateStats = "0.10.3"
Optim = "1.13.3"
Printf = "1.11.0"
PyPlot = "2.11.6"
Random = "1.11.0"
RestrictedBoltzmannMachines = "5.1.1"
SequenceLogos = "0.2.1"
Serialization = "1.11.0"
SparseArrays = "1.12.0"
Statistics = "1.11.1"
StatsPlots = "0.15.8"
XLSX = "0.10.4"
